
spring:
 datasource:
  password: password
  url: jdbc:mysql://localhost:3306/server
  username: user_db
 jpa:
  hibernate:
   ddl-auto: create
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    format_sql: true
  show-sql: true